model:
  arch: fcn8s-vgg16
data:
  dataset: scanNet
  n_class: 20
  img_h: 484
  img_w: 648
  root_dir: ".\\"
  train_file: ".\\train_3000from0123.csv"
  val_file: ".\\val_900from0123.csv"
  mean_file: ".\\Mean_train_1000from012.npy"
  class_weight_file: ".\\class_weight_3000from0123_half.npy"
training:
  epochs: 500
  batch_size: 4
  optimizer:
    name: 'RMSProp'
    lr: 1e-3
    weight_decay: 1e-5
    momentum: 0.5
  loss:
    name: 'BCEWithLogitsLoss'
    size_average: False
  lr_schedule:
    step_size: 10
    gamma: 0.9
  model_dir: ".\\models"